# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
# services:
#   - mysql:latest
#   - redis:latest
#   - postgres:latest
  
# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/
    - server/node_modules/
    - client-web/node_modules

# variables:
#   NODE_ENV: development

stages:
  - test
  - build
  - deploy

# before_script:
  # - cd server

test:
  stage: test
  script: 
    - cd server
    - npm ci --cache .npm --prefer-offline
    - echo "environment:"
    - echo $NODE_ENV
    - echo "Running tests"
    - npm install
    - npx mocha
  artifacts:
    paths:
      - node_modules/
#    - node scripts/index.js
  environment:
    name: development
  except:
  - deploy-test

build:
  stage: build
  script: echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - export NODE_ENV = production
    - echo "Deploy to staging server"
  environment:
    name: staging
    url: https://staging.example.com
  only:
  - deploy-test
  


#test_async:
#  script:
#    - npm install
#    - node ./specs/start.js ./specs/async.spec.js

#test_db:
#  script:
#    - npm install
#    - node ./specs/start.js ./specs/db-postgres.spec.js