version: 0.0

os: linux
files:
  - source: / # This line assumes that your deployment code is located in
    destination: /home/ubuntu/server
permissions:
  # sets application runner script as executable - This example assumes the sample 'server.sh' script has been added to the the directory 'server' and serves as the application launcher
  - object: /home/ubuntu/server/
    pattern: "*.sh"
    owner: ubuntu
    mode: 755
    type:
      - file
  # sets ubuntu as the owner:group for the application deployment directory
  - object: /home/ubuntu/
    pattern: "server"
    owner: ubuntu
    type:
      - directory
hooks:
  # All hook scripts are assumed to be in the /install/aws_cd directory located at the root of the deployment zip archive
  ApplicationStop:
    - location: scripts/app_stop.sh
      timeout: 180
      runas: ubuntu
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 180
      runas: ubuntu
  ApplicationStart:
    - location: scripts/app_start.sh
      timeout: 180
      runas: ubuntu
  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 180
      runas: ubuntu
artifacts:
  files:
    - '**/*'